export const membershipBrands = [
  {
    membership_tap: 'VIP 콕',
    membership_brand: '할리스',
    membership_description: '아메리카노(R사이즈) 1잔 무료\n※ ICE/HOT 선택 가능',
    membership_grade: 'VIP',
    logo: '/map/hollys.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: 'CGV',
    membership_description:
      '무료 예매 연 3회 / 1+1 예매 연 9회(총 12회)\n(월 1회 사용 가능, CGV/메가박스 중 택 1)\n※ 1+1이란? 1매 유료로 구매 시, 1매 무료 제공',
    membership_grade: 'VIP',
    logo: '/map/CGV.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '롯데월드 어드벤처 부산',
    membership_description: '종합이용권(1 Day / AFTER 4)본인 35% 할인 (동반 3인 10%)',
    membership_grade: 'VIP',
    logo: '/map/lotte.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '에버랜드',
    membership_description: '종일권 본인 40% 할인(대인/소인)',
    membership_grade: 'VIP',
    logo: '/map/ever.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '캐리비안베이',
    membership_description: '이용권 본인 40% 할인\n (동반 1인 30% 할인)',
    membership_grade: 'VIP',
    logo: '/map/caribbean.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '배스킨라빈스',
    membership_description: '싱글레귤러 1개 무료 교환',
    membership_grade: 'VIP',
    logo: '/map/BR.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '쉐이크쉑',
    membership_description: '2만원 이상 구매 시 5천원 할인',
    membership_grade: 'VIP',
    logo: '/map/shake.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '메가박스',
    membership_description:
      '무료 예매 연 3회 / 1+1 예매 연 9회\n(월 1회 사용 가능, CGV/메가박스 중 택 1)',
    membership_grade: 'VIP',
    logo: '/map/megabox.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '뮤지엄L',
    membership_description: '뮤지엄엘 1관(모나리자 이머시브) 전시 1인 무료 입장권',
    membership_grade: 'VIP',
    logo: '/map/museum.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '롯데월드 어드벤처',
    membership_description: '본인 종합이용권(1 Day / AFTER 4) 42% 할인\n (동반 1인 30% 할인)',
    membership_grade: 'VIP',
    logo: '/map/lotte.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: '롯데월드 아쿠아리움',
    membership_description: '본인 입장권 40%할인\n(동반 최대3인까지 30%할인)',
    membership_grade: 'VIP',
    logo: '/map/lotteaq.png',
  },
  {
    membership_tap: 'VIP 콕',
    membership_brand: 'SEOUL SKY',
    membership_description: '본인 입장권 30%할인\n(동반인 최대 3인까지 10%할인)',
    membership_grade: 'VIP',
    logo: '/map/seoul.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'CGV',
    membership_description: '2D영화 2천원 할인',
    membership_grade: 'BASIC',
    logo: '/map/CGV.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'GS THE FRESH',
    membership_description: 'VVIP/VIP 3천원 할인\n우수 2천원 할인\n※ 5만원 이상 결제 시',
    membership_grade: 'BASIC',
    logo: '/map/GSthefresh.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'GS25',
    membership_description:
      'VVIP/VIP : 1천원 당 100원 할인\n 우수 : 1천원 당 50원 할인\n※제휴사 지정하는 행사상품은 할인제외',
    membership_grade: 'BASIC',
    logo: '/map/GS25.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '파리바게뜨',
    membership_description: 'VVIP/VIP  : 1천원당 100원 할인\n 우수 : 1천원당 50원 할인',
    membership_grade: 'BASIC',
    logo: '/map/paris.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '뚜레쥬르',
    membership_description:
      'VVIP : 1천원당 150원 할인\n VIP : 1천원당 100원 할인\n 우수 : 1천원당 50원 할인',
    membership_grade: 'BASIC',
    logo: '/map/TJ.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '젠지 글로벌 아카데미',
    membership_description:
      '젠지 글로벌 아카데미 게임교육프로그램 취미반 Play 30% 할인\n※타 쿠폰과 중복사용 불가',
    membership_grade: 'BASIC',
    logo: '/map/gen.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '배스킨라빈스',
    membership_description: '패밀리 사이즈(5가지 맛) 4천원 할인',
    membership_grade: 'BASIC',
    logo: '/map/BR.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'VIPS',
    membership_description: 'VVIP/VIP : 15% 할인\n 우수 : 5% 할인',
    membership_grade: 'BASIC',
    logo: '/map/vips.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '더플레이스',
    membership_description: 'VVIP/VIP : 15% 할인\n 우수 : 5% 할인',
    membership_grade: 'BASIC',
    logo: '/map/theplace.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '제일제면소',
    membership_description: 'VVIP/VIP : 15% 할인\n 우수 : 5% 할인',
    membership_grade: 'BASIC',
    logo: '/map/제일제면소.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '롯데시네마',
    membership_description: '4천원 할인',
    membership_grade: 'BASIC',
    logo: '/map/l-c.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '유가네닭갈비',
    membership_description:
      'VVIP/VIP : 10% 할인\n 우수 : 5% 할인\n(2만원 이상 주문 시, 최대 4천원)',
    membership_grade: 'BASIC',
    logo: '/map/yoogane.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '라그릴리아',
    membership_description: 'VVIP/VIP 등급 : 10% 할인 \n 우수 : 5% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '반올림피자',
    membership_description: '전 등급 20% 할인',
    membership_grade: 'BASIC',
    logo: '/map/반올림.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '빛의 벙커',
    membership_description: '입장권 20% 할인(동반 1인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '빛의 시어터',
    membership_description: '입장권 30% 할인(동반 1인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '그라운드시소',
    membership_description: '그라운드시소 전시장 일괄 티켓 최대 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '서울드래곤시티',
    membership_description: '식음료 매장에서 코스 메뉴 주문 시 10% 할인 + 소프트 드링크 1개 제공',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '굽네치킨',
    membership_description: '굽네치킨 2,500원 할인 쿠폰 1매\n※1만7천원이상 주문시 사용가능',
    membership_grade: 'BASIC',
    logo: '/map/goobne.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '컬리너리스퀘어',
    membership_description: '10%할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '뽀로로파크',
    membership_description: '뽀로로파크 입장권 본인 40% 할인+동반 1인 30% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '아쿠아필드',
    membership_description: '찜질스파 또는 워터파크 주중 30% 할인 (최대 2인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '스파랜드',
    membership_description: '스파랜드 입장권 주중 30% 할인 (최대 2인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '원더빌리지',
    membership_description: '원더빌리지 입장권 25% 할인 (최대 4인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '원더파크',
    membership_description: '원더파크 입장권 25% 할인 (최대 4인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '파리크라상',
    membership_description: 'VVIP/VIP  : 1천원당 100원 할인\n 우수 : 1천원당 50원 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '메가박스',
    membership_description:
      '①VVIP/VIP : 4천원 할인\n우수 : 2천원 할인\n②오리지널/카라멜팝콘 L 4천원 구매권 or 콤보 3천원 할인권(예매 건당 1매)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '뮤지엄 원',
    membership_description: '최대 33% 현장 할인 (본인 포함 4인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '다락',
    membership_description: 'VVIP/VIP : 월 이용금액 1개월 무료 + 35% 할인 \n 우수 : 35% 할인',
    membership_grade: 'BASIC',
    logo: '/map/daLock.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '클럽디 오아시스',
    membership_description: '10% 할인 (통합권/워터파크/스파권)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '신라면세점(오프라인)',
    membership_description: '①등급업\n②추가할인\n③쇼핑지원금 증정',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '부산 엑스 더 스카이',
    membership_description: '입장권 25% 할인 (동반 1인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '코엑스아쿠아리움',
    membership_description: '입장권 15% 할인(동반 3인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '아쿠아플라넷',
    membership_description: '①일산점, 광교점 20% 할인\n②여수점, 제주점 15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '부산아쿠아리움',
    membership_description: '입장권 25% 할인 (동반 1인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '세빛섬',
    membership_description:
      '세빛섬 내 제휴 레스토랑 할인\n (채빛퀴진뷔페/이솔라레스토랑/카페돌체/골든블루마리나)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '화담숲',
    membership_description: '광주시민/외국인 현장발권시 입장권 1천원 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '캐리비안베이',
    membership_description: '20% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '서울랜드',
    membership_description:
      'VVIP/VIP : 종합이용권 50% 할인(동반 1인 30% 할인)\n 우수 : 종합이용권 40% 할인(동반 1인 30% 할인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '롯데월드 아이스링크',
    membership_description: '입장권 50% 할인 (동반 1인 포함)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'LG트윈스 경기 티켓 할인',
    membership_description: 'VVIP/VIP : 3천원 할인\n 우수 : 2천원 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '대관령 하늘목장',
    membership_description: '대인 3천원 할인 / 소인 2천원 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '롯데월드 아쿠아리움',
    membership_description: '본인 30% + 동반3인 30%',
    membership_grade: 'BASIC',
    logo: '/map/lotteaq.png',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '제주민속촌',
    membership_description: '입장권 20% 할인 (동반 3인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '이월드',
    membership_description: '종합이용권 40% 할인 (동반 최대3인 20%할인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: 'SEOUL SKY',
    membership_description: '본인 20%(동반3인 10%)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '대구아쿠아리움',
    membership_description: '입장권 20% 할인(동반 1인 포함)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '뽀로로아쿠아빌리지',
    membership_description: '입장권 35% 할인(본인 포함 3인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '곤지암리조트',
    membership_description:
      '[객실]U+멤버십패키지 최대 10% 할인 및 카페 라운지 음료 쿠폰 2매\n[스파]패밀리스파 입장료 최대 30% 할인(본인포함 4인까지)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '롯데월드 어드벤처 부산',
    membership_description: '종합이용권(1 Day / AFTER 4) 본인 25% 할인 (동반 3인 10%)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '한강유람선 이크루즈',
    membership_description:
      '①스토리 크루즈, 뮤직 크루즈, 달빛 크루즈 : 20% 할인(동반 1인 포함)\n②런치 크루즈, 디너 크루즈 : 10% 할인(동반 1인 포함)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '롯데면세점(오프라인)',
    membership_description: '①등급 업\n ②LDF PAY 증정\n ③할인쿠폰 증정',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '신라아이파크면세점(오프라인)',
    membership_description: '①용산점 등급업\n ②선불카드 1만원 증정',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '신세계면세점(오프라인)',
    membership_description: '①GOLD 멤버십 부여\n ②쇼핑지원금 2종 2만원 증정',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '더반찬＆',
    membership_description: '3천원 할인 (3만원 이상 결제 시)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '전자랜드',
    membership_description: '등급별 할인쿠폰 + 포인트 지급',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '오가나셀 피부과의원 청담점',
    membership_description:
      'VVIP/VIP : 스킨케어, 제모 20% 할인 + 결제 시 13만원 상당 재생 또는 미백 관리 무료 \n우수 : 스킨케어, 제모 20% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '씨네폭스',
    membership_description: '20% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '포토블루',
    membership_description: '가족사진 촬영 무료 (액자비 2만원 본인 부담)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '데이원클리닉',
    membership_description: '스킨케어, 제모 15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '포쉬네일',
    membership_description: '손, 발 기본 젤 또는 남자 손, 발 케어 10% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '유앤아이피부과의원',
    membership_description: '스킨케어, 제모 20% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '자란다',
    membership_description:
      '돌봄, 배움 1회 방문 서비스 할인 (신규 회원 5천원 할인 / 기존 회원 2천원 할인)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '도미노피자',
    membership_description: 'VVIP/VIP : 20% 할인\n 우수 : 15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '미스터피자',
    membership_description: 'VVIP/VIP : 20% 할인\n 우수 : 15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '파파존스',
    membership_description: 'VVIP/VIP : 30% 할인\n 우수 : 15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '피자헛',
    membership_description: '15% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '브레댄코',
    membership_description: '10% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '초심스터디카페',
    membership_description: '3천원 할인 (1만원 이상 결제 시)',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '온더보더',
    membership_description: '10% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '푸드엠파이어',
    membership_description: '10% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '싱카이',
    membership_description: '10% 할인',
    membership_grade: 'BASIC',
  },
  {
    membership_tap: '기본 혜택',
    membership_brand: '오토오아시스',
    membership_description: '엔진오일 2만2천원 할인',
    membership_grade: 'BASIC',
  },
]
